/**
 * ID3 Manager Tests
 *
 * Tests for the ID3 tag management functionality.
 */

import { describe, it, expect, beforeEach } from 'vitest';
import { ID3Manager, createID3Manager } from '../../../src/services/audio/id3-manager.js';

describe('ID3Manager', () => {
  let manager: ID3Manager;

  beforeEach(() => {
    manager = createID3Manager();
  });

  describe('constructor', () => {
    it('should create manager with default config', () => {
      const mgr = new ID3Manager();
      expect(mgr).toBeInstanceOf(ID3Manager);
    });

    it('should accept custom config', () => {
      const mgr = new ID3Manager({
        defaultArtist: 'Custom Artist',
        defaultAlbum: 'Custom Album',
        defaultGenre: 'Speech',
      });
      expect(mgr).toBeInstanceOf(ID3Manager);
    });
  });

  describe('generateDebateTags', () => {
    it('should generate tags with debate ID and proposition', () => {
      const tags = manager.generateDebateTags('debate-123', 'Should AI be regulated?');

      expect(tags.title).toBe('Should AI be regulated?');
      expect(tags.artist).toBe('ClearSide AI Debate');
      expect(tags.album).toBe('Debate Analysis');
      expect(tags.genre).toBe('Podcast');
      expect(tags.year).toBe(new Date().getFullYear().toString());
      expect(tags.comment).toContain('debate-123');
    });

    it('should truncate long propositions in title', () => {
      const longProposition = 'A'.repeat(150);
      const tags = manager.generateDebateTags('debate-123', longProposition);

      expect(tags.title.length).toBeLessThanOrEqual(100);
      expect(tags.title).toContain('...');
    });

    it('should not truncate short propositions', () => {
      const shortProposition = 'Short question?';
      const tags = manager.generateDebateTags('debate-123', shortProposition);

      expect(tags.title).toBe(shortProposition);
      expect(tags.title).not.toContain('...');
    });

    it('should include generation timestamp in comment', () => {
      const tags = manager.generateDebateTags('debate-123', 'Test question');

      expect(tags.comment).toContain('Generated by ClearSide');
    });

    it('should include tagline in comment', () => {
      const tags = manager.generateDebateTags('debate-123', 'Test question');

      expect(tags.comment).toContain('Think both sides. Decide with clarity.');
    });
  });

  describe('generateCoverArt', () => {
    it('should return undefined (placeholder)', async () => {
      const art = await manager.generateCoverArt('Test proposition');
      expect(art).toBeUndefined();
    });
  });
});

describe('createID3Manager', () => {
  it('should create an ID3Manager instance', () => {
    const manager = createID3Manager();
    expect(manager).toBeInstanceOf(ID3Manager);
  });

  it('should pass config to manager', () => {
    const manager = createID3Manager({
      defaultArtist: 'Test Artist',
    });

    const tags = manager.generateDebateTags('id', 'Question');
    expect(tags.artist).toBe('Test Artist');
  });
});
